Println("ENCOMENDA")
Println("\n=============================================")
Println("Pedido 1: bolo_chocolate")
Println("---------------------------------------------")
Println("Receita adaptada para 0 porções:")
Println("\nIngredientes:")
Println("- leite_condensado: 0g")
Println("- chocolate_em_po: 0g")
Println("- manteiga: 0g")
Println("\nPlano de execução:")
Println("2. Resfriar por 30 minutos.")
Println("3. Decorar com granulado.")
Println("\nTempo estimado:")
Println("- Resfriamento: 30 minutos")
Println("- Decoração: 20 minutos")
Println("\nTempo total previsto: 50 minutos")
Println("Limite do pedido: 120 minutos")
Println("Status: Dentro do limite")
Println("\n=============================================")
Println("Pedido 2: brigadeiro")
Println("---------------------------------------------")
Println("Receita adaptada para 0 porções:")
Println("\nIngredientes:")
Println("\nPlano de execução:")
Println("\nTempo estimado:")
Println("\nTempo total previsto: 20 minutos")
Println("Limite do pedido: 0 minutos")
Println("Status: Fora do limite")
Println("\n=============================================")
}
