func main() {
Println("ENCOMENDA")
Println("=============================================")
Println("Pedido 1: bolo_chocolate")
Println("---------------------------------------------")
Println("Receita adaptada para 16 porções:")
Println("Ingredientes:")
Println("- farinha: 600 g")
Println("- acucar: 400 g")
Println("- chocolate: 200 g")
Println("- ovos: 8 unidades")
Println("Plano de execução:")
Println("1. Assar a 180°C por 40 minutos.")
Println("2. Resfriar por 20 minutos.")
Println("3. Decorar com cobertura de chocolate.")
Println("Tempo estimado:")
Println("- Forno: 40 minutos")
Println("- Resfriamento: 20 minutos")
Println("- Decoração: 20 minutos")
Println("Tempo total previsto: 80 minutos")
Println("Limite do pedido: 180 minutos")
Println("Status: Dentro do limite")
Println("=============================================")
Println("Pedido 2: brigadeiro")
Println("---------------------------------------------")
Println("Receita adaptada para 120 porções:")
Println("Ingredientes:")
Println("- leite_condensado: 1580 g")
Println("- chocolate_em_po: 120 g")
Println("- manteiga: 80 g")
Println("Plano de execução:")
Println("2. Resfriar por 30 minutos.")
Println("3. Decorar com granulado.")
Println("Tempo estimado:")
Println("- Resfriamento: 30 minutos")
Println("- Decoração: 20 minutos")
Println("Tempo total previsto: 50 minutos")
Println("Limite do pedido: 120 minutos")
Println("Status: Dentro do limite")
Println("=============================================")
}
