func main() {
Println("ENCOMENDA")
Println("=============================================")
Println("Pedido 1: mega_bolo")
Println("---------------------------------------------")
Println("Receita adaptada para 200 porções (2.0 vezes a receita base)")
Println("Ingredientes:")
Println("- farinha: 4000 g")
Println("- acucar: 3000 g")
Println("- ovos: 160 unidades")
Println("- manteiga: 2000 g")
Println("Plano de execução:")
Println("1. Assar a 180°C por 120 minutos.")
Println("2. Resfriar por 60 minutos.")
Println("3. Decorar com glacê real.")
Println("Tempo estimado:")
Println("- Forno: 120 minutos")
Println("- Resfriamento: 60 minutos")
Println("- Decoração: 20 minutos")
Println("Tempo total previsto: 200 minutos")
Println("Tempo disponível para produção: 360 minutos")
Println("Status: Dentro do limite de tempo")
Println("=============================================")
}
